#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

if [[ -e .custom_sh_rc ]]; then
  source .custom_sh_rc
fi
. "$HOME/.cargo/env"
